### ISSUE TITLE
Actualizar los datos, distinguiendo NA de ceros en los valores de cuadrantes

### ISSUE THREAD

**Issue by iramosp** [CONABIO/GEF-Agrobiodiversity#12]
Acordamos que los ceros correspondan a las etiquetas No se consume / compra / vende, mientras que los NA se usen cuando no se realizó la ubicación en cuadrantes.

**Comment by APonce73** [comment]
Listo ya quedó... les puse "NA"s correspondientes al grupo "otros" lo cual significa que "no se realizó" como acordamos. Directamente en la base de datos aparece como una celda vacía en el excel file. 
Envio al correo las bases de datos con esta corrección
