### ISSUE TITLE
Revisión inicial de los datos de nutrición

### ISSUE THREAD

**Issue by iramosp** [CONABIO/GEF-Agrobiodiversity#14]
- [x] Revisar las definiciones de las columnas en el informe de Tablas de composición de alimentos e identificar las que no estén explicadas. 
- [x] Preparar dudas para resolverlas en una reunión con el equipo de nutrición.

**Comment by AliciaMstt** [comment]
Hacer lista de preguntas y ver primero cuales pueden contestar Irene/Amanda. Las que no, ya se las pasamos a Nutrición.

**Comment by iramosp** [comment]
Aquí está el documento con 1) la descripción y observaciones de las columnas de la tabla, y 2) las dudas para Irma / Amanda y Nutrición:
https://docs.google.com/document/d/1NeYAkzYaFwFhkT_M78oJKHw9tvsQHpNWeV6qbL_clBE/

Siguientes pasos: 

- [ ] Reunión con Irma para resolver dudas (5 ago)
- [ ] Avisar a Nutrición de las inconsistencias y dudas

**Comment by iramosp** [comment]
De la reunión con Irma ya quedaron varias dudas resueltas del [documento que teníamos](https://docs.google.com/document/d/1NeYAkzYaFwFhkT_M78oJKHw9tvsQHpNWeV6qbL_clBE/), como las abreviaturas que faltaban y las referencias a los métodos; varias quedaron pendientes para resolverlas con Nutrición.

Acuerdos y siguientes pasos de la reunión con Irma (5 ago):

1. Sobre este nuevo [drive](https://docs.google.com/document/d/1vbh7Rbw7UIHPWugTjcP30STeA0kCjz6DbKdRu2eP7vc/edit#) ir armando el documento “DUDAS” para nutrición. Empezar explicando que hicimos una revisión inicial de la base de datos con el objetivo de ver los modelos que se harían con ella, y de forma muy general en qué consistió la revisión.
2. Completar con capturas de pantalla y ejemplos las dudas para armar un documento con el que se pueda preguntar a Nutrición. 
3. Irma nos da el VoBo del documento “DUDAS”.
4. Posible reunión con Vicente, Amanda, Fran, Caro y nosotros (Irma, Irene, Alicia y Alex) antes de pasar con Nutrición.
5. Pedir a Vicente que contacte al Dr. Aguilar de Nutrición para resolver las dudas (dependerá del punto anterior).

**Comment by AliciaMstt** [comment]
De la reunión con Vicente, Amanda y Fran ([documento guia](https://docs.google.com/document/d/19jnGz9O9YhstQT2vEA2TYWVhamGGqmWi/edit)) se concluyó:

Nos enfocamos en entender la base del 2019 (excel y pdf) y no hacemos comparaciones con la del 2015 para no crear confusión. 

Amanda e Irma hablarán con Bourges sobre las siguientes dudas para preguntarle si (a) la base de datos es la versión final y (b) si se nos autoriza para hacer las modificaciones pertinentes sobre los puntos:

* La base de datos entregada en excel 2019 tiene invertidos los kjouls y kcal en algunos renglones

 * Consultar la existencia de datos de : 
Ácidos grasos monoinsaturados (A. G. M. I.), Ácidos grasos polinstarurados (A. G. P. I.), vitamina B6 [Piridoxina] (Vit. B6), vitamina B12 [Cobalamina] (Vit. B12), ácido Fólico (Ac. Fólico), Folato (µg DFE) y Vitamina D (Vit. D). 

Posibilidad de contar con el archivo excel de los Anexos (decir los que están ya en pdf), así como con la información existente sobre 1. (índice glucémico),  5. (Factores de Conversión), 6 (Ingestión diaria recomendada (IDR) e ingestión diaria sugerida (IDS) de vitaminas y nutrimentos inorgánicos para la población mexicana) y 7 (Recomendaciones de ingestión diaria de proteínas, hidratos de carbono y lípidos para la población mexicana). 

Confirmación sobre si, los números de la columna de referencias de la tabla en formato excel y sus bibliografías específicas.
