### ISSUE TITLE
Subir datos grupos enfoque a nueva instancia

### ISSUE THREAD

**Issue by AliciaMstt** [CONABIO/GEF-Agrobiodiversity#17]
- [x]  Generar datos (script Irene) 
- [x] Subirnos a nueva instancia (Vero)

**Comment by AliciaMstt** [comment]
Bugs que encontró Vero en el proceso de subir los datos:

1.- Escribí "tipo_plata" en lugar de "tipo_planta" en uno de los atributos.
2.- BulkAdd no sirve en el SPA porque no está actualizado con el esquema. BulkAdd regresa un String y el SPA sigue estando con la versión anterior que regresa un arreglo de records.
(sin embargo el bulkAdd puede ser usado desde el API sin usar el SPA)
3.- Los datos de Sitio y GruposFocales no se pudieron subir porque el id de sitio aunque está marcado como string contiene puros números (ejemplo; sitio_id:"311040019") y AJV valida esta entrada con si fuera un entero, por lo tanto manda un error de validación ya que espera un string.

Creará los issues en Zendro necesarios para resolverlo.

**Comment by vsuaste** [comment]
Los issues en Zendro fueron creados y resueltos.
La nueva instancia ya está arriba con los datos de los modelos: `tipo_planta`, `cuadrante` y `sitio`.
Falta subir datos del modelo `grupo_enfoque`, los cuales están siendo revisados porque tienen inconsistencia con los IDs.

**Comment by iramosp** [comment]
Respecto a la inconsistencia de los ID del modelo `grupo_enfoque`, se debe a que el número de participantes no es único por tipo de planta, lo cual ocasiona que los casos inconsistentes se tomen como grupos separados pero con el mismo ID. 

Los grupos inconsistentes son: `2019-08-10_160730008_Hom`, `2019-09-07_160650006_Hom`, `2019-09-07_160650006_Muj`, `2019-10-24_070630008_Muj`, donde las claves corresponden a `fecha_region_tipoGrupo` según acordamos en reuniones previas.

@APonce73 revisará esos registros inconsistentes.

**Comment by AliciaMstt** [comment]
Alex ya envió los datos, Irene los revisa y pasa a Vero, Vero sube a instancia.

Antes de cerrar el issue Alicia, Irene y Alex revisan cómo se ven en la SPA y que todo esté en orden.

**Comment by vsuaste** [comment]
Ya subí los datos arreglados y no hubo problema. 
Los revisan y me dicen si quieren hacer algunos cambios.

**Comment by APonce73** [comment]
Hola... no se que es el SPA @AliciaMstt, pero con el vobo de usd para mi esta bien... ya que los datos pasaron bien

**Comment by APonce73** [comment]
listo... ya lo chequé... (gracias a @iramosp  por recordarme como entrar a el SPA). Me gustó mucho... la parte de cuadrantes pensé al inicio que sólo eran 25.... pero ya ví que son más de dos mil registros....
Pienso que sería bueno en alguna parte una info básica sobre Que es un grupo de enfoque. yo puedo escribir esto e incluso tenemos fotos (aunque hay rostros y parece que hay todo un show con los rostros, permisos, autorizaciones, etc etc.)
Que feliz me hizo ver los datos en Zendro.... 
Welldone!!

**Comment by iramosp** [comment]
Hola, yo también ya lo revisé y se ven bien. 
Coincido con @APonce73 en que todavía nos falta una sección para metadatos, incluyendo el diccionario de datos, etc. Por lo mientras, está lista esta primera parte.
