### ISSUE TITLE
Kobo issue migración a almacenamiento privado

### ISSUE THREAD

**Issue by AliciaMstt** [CONABIO/GEF-Agrobiodiversity#18]
Usuario del proyecto R016 recibió una notificación en la app android que dice "se debe migrar los formularios a un almacenamiento privado antes de Agosto 2020 para dar cumplimiento a los nuevos requisitos de Android"

¿?

**Comment by framirez07** [comment]
Acorde a la información en el siguiente link (que Oswa me compartió), es necesario y sin riesgos, realizar la migración solicitada en la aplicación Android:

https://forum.getodk.org/t/odk-collect-v1-26-storage-migration/25268

**Comment by AliciaMstt** [comment]
Perfecto ¿Acordaste con Oswa que se le avise a lxs usuarixs? De no ser así, creo que valdría la pena explicar esto todxs lxs usuarixs por correo electrónico, incluyendo nuestro registro (correos del serividor de kobo) así como a lxs responsables de los proyecto gef (Oswa y Alex deben saber quienes son, por si sus direcciones de correo no son las del servidor de kobo).

**Comment by framirez07** [comment]
Se enviaron correos a usuarios KoBo y a resonsables gef.
