### ISSUE TITLE
Agregar bases y prioridades a lista de bases

### ISSUE THREAD

**Issue by AliciaMstt** [CONABIO/GEF-Agrobiodiversity#9]
En la tabla de bases de datos que se integraran al SiAgro, es necesario agregar las bases de nuevos proyectos de colaboración, y priorizar el orden en el que trabajaremos en las bases

https://docs.google.com/spreadsheets/d/1vOyDgfaO31YGqHxz8Nbs_KvsPXO_VoCibOJdeR0HFTM/edit#gid=0

**Comment by AliciaMstt** [comment]
Agregué las bases que hemos comentado con instituciones externas y la columna "Prioridad". En esta Números cercanos a 1 tienen mayor prioridad. Bases cuya prioridad no se ha discutido se marcan como "por definir". 

@APonce73  o @iramosp por favor revisen si están de acuerdo y si todo está claro, y de ser así cierren este issue.

**Comment by APonce73** [comment]
Estoy de acuerdo.
Perdón por el retraso
